server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: test
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 25MB
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://fixel-dev.cbmyxewpbi2k.ap-northeast-2.rds.amazonaws.com:3306/schema_vc?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: fixel
    password: fixel123

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.caddie.voice.y1.domain

logging:
  level:
    root : INFO
    org:
      springframework:
        cloud:
          gateway: TRACE